DROP TABLE IF EXISTS SSOUser;

CREATE TABLE SSOUser (
       ID INT NOT NULL AUTO_INCREMENT
     , Username VARCHAR(60) NOT NULL
     , Password VARCHAR(40) NOT NULL
     , UNIQUE UQ_USER_1 (ID)
     , PRIMARY KEY (ID)
);
